### ISSUE TITLE
Issues with $this->CanonicalUrl Populating Correctly in controllers/SearchController.php?

### ISSUE THREAD

**Issue by supert3d** [lightspeedretail/webstore#569]
Most of the other views seem OK. Just when selecting brands/designers. $this->CanonicalUrl appears to be malformed. 

View (HTML) Source: 
[code]
&lt;link rel="canonical" href="http://shop.wheninroam.com/http://shop.wheninroam.com/brand/213-industry"/&gt;
[/code]

**Comment by gabeguz** [comment]
Closing as duplicate of #630
