### ISSUE TITLE
Store with Taxed prices only, still shows tax-free prices

### ISSUE THREAD

**Issue by hakonorri** [lightspeedretail/webstore#575]
Using the webstore wanting only to display prices with tax (in Europe) the webstore still shows prices without tax until the customer fills in their shipping address. Then the calculator adds the tax. 
This annoyes the customer since it is tradition (and legally a must) to display prices with tax.
Can you fix so the store never displays prices without tax?

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
