### ISSUE TITLE
Autoupdate is broken on windows

### ISSUE THREAD

**Issue by Dragony** [lightspeedretail/webstore#577]
In the Upgrade controller unzipping the upgrade file always fail because of the following:
```php
protected function unzipFile($path,$file)
{
    $path = str_replace("/core/protected","/runtime/upgrade",Yii::app()->basePath);

    die($path);
    // Results in "C:\xampp\htdocs\projectname\core\protected"

    require_once( YiiBase::getPathOfAlias('application.components'). '/zip.php');
    extractZip($file,'',$path);
    return true;
}
```
The str_replace does not work on windows, because basePath returns a value delimited with backwards slashes, but the replace only replaces the path correctly with forward slashes.

It's a windows server because I'm running windows on my dev machine.

**Comment by gabeguz** [comment]
This won't be fixed.  We don't support install/running on Windows. Sorry.
