### ISSUE TITLE
Mailchimp subscriber not created on checkout

### ISSUE THREAD

**Issue by noahkuhn** [lightspeedretail/webstore#579]
I've been trying to get bug fixes through the support team to the right person and haven't had any satisfaction so I'm adding things here in the hopes that the actual developers of the Web Store can actually fix some of the bugs that are present in this software.

If the Mailchimp settings are set up, and someone checks the box to "send me stuff" when they check out, AND they enter a password so their account is saved, they don't get added to Mailchimp.

The only way for them to do it is to go into their account after having signed up and checking the box.

Please fix.

**Comment by ottaz** [comment]
This issue has been fixed in [v3.3.4](https://github.com/lightspeedretail/webstore/tree/3.3.4)
