### ISSUE TITLE
Credit Card dropdown ordering display

### ISSUE THREAD

**Issue by noahkuhn** [lightspeedretail/webstore#583]
I've been trying to get bug fixes through the support team to the right person and haven't had any satisfaction so I'm adding things here in the hopes that the actual developers of the Web Store can actually fix some of the bugs that are present in this software.

Can't see any way in the web control panel to Order the display of the credit cards. In the DB there is a xlsws_credit_card.sort_order field which appears to control the ordering, but there is no way outside of directly editing the database to modify the values...

**Comment by gabeguz** [comment]
Hi @noahkuhn --- unfortunately there are currently no plans to implement this feature in the webstore admin, and our internal bug WS-1132 has been closed with a "will revisit in the future" message.    I'm closing this issue here as well.
