### ISSUE TITLE
Cancelling PayPal payment results in an error

### ISSUE THREAD

**Issue by hakonorri** [lightspeedretail/webstore#587]
I get this error when I return to webstore from PayPal (if I click "Cancel and return to Storenamexxx").

Error 500
CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`hakon_lalujo3`.`xlsws_customer`, CONSTRAINT `xlsws_customer_ibfk_1` FOREIGN KEY (`default_billing_id`) REFERENCES `xlsws_customer_address` (`id`))

No payment was done. 

I would like to go to the active cart again.

**Comment by euoia** [comment]
Fixed in 3.1.0.
