### ISSUE TITLE
Installation Issue:  Installing Amazon categories (group 2 of 14)

### ISSUE THREAD

**Issue by doug123** [lightspeedretail/webstore#593]
Hi Friends,

I'm trying to install the Lightspeed Web Store & the following error has occurred:

Server appears to be throttling connections, setting delay to 163seconds
Installing Amazon categories (group 2 of 14)

It's stuck at this point and isn't going anywhere fast.

Any ideas what I can do to correct this?  Is there an error log?

Thank you for any help.

**Comment by lithiumlab** [comment]
I'm installing the webstore on a 3rd party hosting for a frontend integration purposes with a client's website.
After solving some environment issues i finally got trough the installation process but it seems to get stuck here for more than 10 minutes and counting...

```
Server appears to be throttling connections, setting delay to 36seconds
Downloading default template...
```

Even if the message is self explanatory, do you have a suggestion on how to solve this under Windows Server 2008 R2?

**Comment by gabeguz** [comment]
Hi @lithiumlab we don't support installation on Windows, so I don't really know what could go wrong.  For one thing, we're not using DIRECTORY_SEPERATOR everywhere so there are likely many things that won't work properly on windows.  Maybe someone else has experience setting up Web Store on windows, but like I said, it's not an officially supported system.

**Comment by lithiumlab** [comment]
Thanks for the quick reply.
This helped me a lot to clarify. Thanks.
