### ISSUE TITLE
Custom Page content not saved when initially creating new custom page

### ISSUE THREAD

**Issue by tylerforesthauser** [lightspeedretail/webstore#600]
I've found that when you go to create a new custom page and you include content in the Edit Page Content field, that content does not get saved on that first save. After that initial save, however, it works as expected.

Running 3.1.4 (Build webstore-2014-04-15-1553)

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
