### ISSUE TITLE
FB.init has already been called

### ISSUE THREAD

**Issue by tylerforesthauser** [lightspeedretail/webstore#608]
The moment you set up Facebook connect, this warning shows up in browser consoles.

`FB.init has already been called - this could indicate a problem`

Using default Brooklyn theme on Web Store version 3.1.5.

**Comment by gabeguz** [comment]
@tylerforesthauser Can you confirm if this is still happening in 3.2.2?  I'm unable to reproduce it at the moment.

**Comment by tylerforesthauser** [comment]
@gabeguz Yes, I'm afraid it's still happening in 3.2.2 and using Brooklyn 2014 theme. And, of course, requires Facebook Connect to be configured. As soon as you remove the Facebook App ID or Facebook Secret Key, the warning does not show up.

**Comment by gabeguz** [comment]
@tylerforesthauser Hmm, strange, can you give me more details so I can try to reproduce this?  If I configure Facebook Connect in the admin and then start browsing the webstore, I don't see any error messages in my JS console.   Is it on every page?  Only certain pages?  Do you have "Show Facebook Comments On Product Details:" or "Show Post To Wall After Checkout:" enabled?   I've tried with both of those on a fresh webstore install and I'm not seeing the warning you mention.   What browser?

**Comment by tylerforesthauser** [comment]
@gabeguz It seems to be every page and it's present in Safari 8.0.3, Google Chrome 40.0.2214.115 and Firefox 35.0.1 on Mac OS X 10.10.2. Turning those options on or off makes no difference. Could it be unique to our Facebook Connect information? The test site I setup can be found [here](http://themacpros.ca/dev/webstoremaster/).

**Comment by gabeguz** [comment]
Thanks, I'm now able to reproduce it locally.

**Comment by gabeguz** [comment]
This is now being tracked internally as WS-4126.
