### ISSUE TITLE
Amazon Downloader Exception w/ HumanNameParser

### ISSUE THREAD

**Issue by wwbs** [lightspeedretail/webstore#610]
Many Amazon orders fail to download correctly because the HumanNameParser throws an exception if the Amazon username is only a single name. Here is a sample of the logged error from a user named 'miaowen'. The cart gets created but does not have any customer info because of this. As a result, it doesn't get sent to LS POS.

exception 'Exception' with message 'Couldn't find a last name in 'miaowen'.' in /site.com/core/protected/extensions/HumanNameParser/Parser.php:150
Stack trace:
#0 /site.com/core/protected/extensions/HumanNameParser/Parser.php(62): HumanNameParser_Parser->parse()
#1 /site.com/core/protected/extensions/HumanNameParser/Parser.php(31): HumanNameParser_Parser->setName('miaowen')
#2 /site.com/core/protected/components/helpers.php(184): HumanNameParser_Parser->__construct('miaowen')
#3 /site.com/core/protected/extensions/wsamazon/wsamazon.php(431): _xls_parse_name('miaowen')
#4 /site.com/core/protected/modules/integration/controllers/CronController.php(60): wsamazon->OnActionListOrders(Object(CEventTaskQueue))
#5 /site.com/core/framework/web/actions/CInlineAction.php(49): CronController->actionIndex()
#6 /site.com/core/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /site.com/core/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /site.com/core/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /site.com/core/framework/web/CWebApplication.php(282): CController->run('')
#10 /site.com/core/framework/web/CWebApplication.php(141): CWebApplication->runController('integration/cro...')
#11 /site.com/core/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /site.com/index.php(38): CApplication->run()
#13 {main}
REQUEST_URI=/integration/cron

**Comment by ottaz** [comment]
This bug has been fixed as of version [3.2.6](https://github.com/lightspeedretail/webstore/tree/3.2.6).
