### ISSUE TITLE
Unable to extend a Model, requires a full copy of the file

### ISSUE THREAD

**Issue by echantigny** [lightspeedretail/webstore#614]
This issue seems to have been present for a good while now and I can't see it in here.  The wiki clearly says it was not working on 3.0.7 and still isn't.  

Copying a full module file is a bit unacceptable because it makes updates bug fixes non-existent for those files.  Adding a method or extending one should work as seemlessly has it does for controllers.

**Comment by gabeguz** [comment]
This is a fundamental problem with how Web Store handles customizations, and not something we'll be able to easily fix.  I'm going to close this with apologies.

**Comment by echantigny** [comment]
Might be time to rethink your system then.  Not being able to customize those things is not something you want with a system.  I am not using it at all anymore so I don't really mind if you fix it or not.  I'm sure a lot of people think the same way.
