### ISSUE TITLE
3.1.6 does not fix Custom Pages in Admin

### ISSUE THREAD

**Issue by jorisw** [lightspeedretail/webstore#616]
After going from 3.0.7 to 3.1.5, the content of Custom Pages in the Admin panel show up empty in the textarea where content can be edited. No change if I switch to source code mode using the button right above the textarea.

The 3.1.6 release notes say this bug is fixed, however after updating to 3.1.6, the textareas are still empty. The custom pages do show correctly still, on the web store itself.

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
