### ISSUE TITLE
Removing family doesn't remove from webstore

### ISSUE THREAD

**Issue by hakonorri** [lightspeedretail/webstore#617]
When I hover over BRANDS (or families) on my website I only see the brands that have products that have items for sale on the webstore. So when a product is sold out the link disappears. This is what I like.

I added a new family in my LIghtspeed when preparing for receiving a new brand. The family appears in http://lalujo.se/brand/%2A (in Brooklyn theme) even though I haven't added a single product to that family. Also in that link I can see "old" families that are sold-out or abandoned.

I removed the new family from LIghtspeed but the family wasn't removed from the Webstore. I had to go into the database to remove it.

Shouldn't http://lalujo.se/brand/%2A show the same brands as when I hover over the Brands link?

**Comment by gabeguz** [comment]
We are tracking this issue internally as WS-51.

**Comment by ottaz** [comment]
This has been fixed as of version [3.2.7](https://github.com/lightspeedretail/webstore/tree/3.2.7).
