### ISSUE TITLE
E-mail used in guest checkout can't register after checkout

### ISSUE THREAD

**Issue by wwbs** [lightspeedretail/webstore#621]
The process for the issue is as follows:

- User completes checkout as a guest
- User later decides to register, goes to the register page and gets error 'Email address already exists in system. Please log in.'
- At login page user doesn't have a password so they use the 'forgot password' link and gets an alert error 'Your email address was not found in our system.'

In the end, guest users are never able to create an account with their guest email because of the email address being in the system according to the register check but not found according to the login/forgot password check. Tested in multiple versions since 3.x and still an issue with 3.1.7.

**Comment by gabeguz** [comment]
We are tracking this internally as WS-805 I don't currently have a fix date for it however.

**Comment by gabeguz** [comment]
Fixed in 3.2.5
