### ISSUE TITLE
Product detail images severely lower quality than source image.

### ISSUE THREAD

**Issue by brandinchiu** [lightspeedretail/webstore#624]
We have a customer loading source images for her products at 800x800px, and have set the adminForm to display the product detail image at 800x800.  However, the image being generated by webstore is pixilated and far lower quality that the source image, even though they are the same resolution.

Are we doing something wrong?

**Comment by gabeguz** [comment]
Thanks for the report, we're tracking this internally as WS-2518.  I currently have no fix date for this however.

**Comment by ottaz** [comment]
This issue has now been fixed as of version [3.2.9](https://github.com/lightspeedretail/webstore/tree/3.2.9).
