### ISSUE TITLE
Search field missing from Brooklyn mobile

### ISSUE THREAD

**Issue by hakonorri** [lightspeedretail/webstore#625]
When you view a site in Brooklyn theme v3 (webstore 3.1.7) on a Mobile device, the search field disappears. Please bring it back. Maybe the best place for it is inside the Menu.

**Comment by gabeguz** [comment]
Hi @hakonorri we did have bug for this in our internal system WS-2195 - however that bug has been closed "no plans to do".  This functionality should be working properly in the Brooklyn2014 theme, however.
