### ISSUE TITLE
Brooklyn product page show "regular price" on regular priced products

### ISSUE THREAD

**Issue by hakonorri** [lightspeedretail/webstore#626]
The text "regular price" is supposed to be only shown on items that are on discount, but in 3.1.7 and 3.1.8 the text is shown on full priced items.

This text appears when you have chosen size of the product on product page

this is valid at least for TAX Inclusive products.

example of full price item: http://lalujo.se/lexi-open-toe-by-michael-kors/dp/3457 and choose a size

**Comment by gabeguz** [comment]
Thanks for the report, this has been linked to our internal bug tracker and given the id: WS-1474
I have no fix date for this bug at the moment.

**Comment by gabeguz** [comment]
More details available here: https://github.com/lightspeedretail/webstore/issues/651

**Comment by ottaz** [comment]
This bug has been fixed as of version [3.2.6](https://github.com/lightspeedretail/webstore/tree/3.2.6).
