### ISSUE TITLE
Google Merchant Feed links to master products

### ISSUE THREAD

**Issue by n-ck** [lightspeedretail/webstore#627]
The Google Merchant feed generated by Lightspeed Web Store links always to the master product, this is not allowed anymore since the latest Google Merchant Center update,the New Landing Page Content Policy (source: https://support.google.com/merchants/answer/3097504?hl=en).

The Google Merchant feed will be suspended if this issue is not fixed, I found the following fix:

File location: /core/protected/controllers/xml/GoogleMerchant.php

Line 80:
echo chr(9).'<link>'.$objProduct->AbsoluteUrl.'</link>'.chr(13);

Replace this with the following line to link to the correct landing pages:

echo chr(9).'<link>http://www.domain.com/'.$objProduct->request_url.'/dp/'.$objProduct->id.'</link>'.chr(13);

**Comment by ottaz** [comment]
This issue has now been fixed as of version [3.2.9](https://github.com/lightspeedretail/webstore/tree/3.2.9).
