### ISSUE TITLE
Keep Github up to date with version releases

### ISSUE THREAD

**Issue by tylerforesthauser** [lightspeedretail/webstore#629]
It is August 27th and Web Store v3.1.11 has just been released. Here on Github, we're sitting at 3.1.9. It would MUCH more helpful to have this up to date so us developers can easily keep track of changes. Thank you kindly.

**Comment by gabeguz** [comment]
Github release just updated to [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2)
