### ISSUE TITLE
Install ERRROR when the server, database or username, has a - or _ , 

### ISSUE THREAD

**Issue by manu14Oranges** [lightspeedretail/webstore#631]
on install.php when $hostname, $dbname or $dbuser have a (- or a _) they are removed, so the conection fails.
I manually added a str_replace function on createDbConnection to overwritte the values.
It took me a while to figure it out. THis is to me a bug, because is common that DB name or USER have a _

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
