### ISSUE TITLE
Bug in the Category Tree order

### ISSUE THREAD

**Issue by echantigny** [lightspeedretail/webstore#635]
There is a major issue in the main controller for the Category Tree menu's order. core/protected/components/Controller.php Line 543 and 566 there is a ksort(). ksort resorts all the categories in alphabetic order, destroying the menu_position order that the Category::getTree() code uses. 

Yes, there is a simple solution with calling the Category::getTree() directly when calling the menu widget, but it should not be necessary and adds a database/cache call.

**Comment by ottaz** [comment]
This bug has been fixed as of version [3.2.6](https://github.com/lightspeedretail/webstore/tree/3.2.6).
