### ISSUE TITLE
Email Order Confirmation does not work with PayPal Simple Integration

### ISSUE THREAD

**Issue by GoblinGaming** [lightspeedretail/webstore#636]
Pretty much as described in title. When orders come through via in store cash sale or papal payments pro ect both the store and the client making the purchase receive an email order confirmation.

However when using the PayPal simple integration (asks customers to sign into paypal and send the money to our paypal account) it does not sent the confirmation email to anyone. This frustrates me because I only know an order has been placed when LightSpeed Pro downloads the orders, more importantly though clients are left wondering if the purchase was a success as there is no email confirmation.

Can anyone shed any light on this bizarre issue?

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
