### ISSUE TITLE
Setting all web prices via set % off RRP as mass update

### ISSUE THREAD

**Issue by jameshall89** [lightspeedretail/webstore#639]
I have a web store with over 600 products in from only 3 suppliers. My margin is fixed on all items but i would like a way of setting the web prices on mass for all items or the ability to specify by supplier ect.

Is there any way to do this currently?

**Comment by gabeguz** [comment]
@GoblinGaming is this still an issue for you, or did you find a way around it?   I'd like to close this issue if it's no longer relevant.  Thanks.

**Comment by ottaz** [comment]
This is something that would need to be done in the governing software i.e. Retail or Onsite. Closing.
