### ISSUE TITLE
Web Store 3.1.12 not using BrooklynCopy custom.css

### ISSUE THREAD

**Issue by w-barath** [lightspeedretail/webstore#640]
This isn't a showstopper - I can still edit the custom CSS via /admin, but it would be nice if the platform performed as documented and as designed.

Steps to reproduce:

1 sign into /admin
2 click Themes then Manage My Themes
3 create a copy of Brooklyn.  Note that the action of copying it will disable custom CSS and make BrooklynCopy the active theme, which was a bit confusing.
4 click Edit CSS for "Brooklyn Copy"  Note the inconsistent use of spaces in the name
5 enable the checkbox for  "Use custom.css with Brooklyncopy." then click [SAVE] - again inconsistent use of space in the name
6 go to the FTP and try to edit /themes/brooklyncopy/css/custom.css
7 return to the admin UI and note that the changes are not reflected
8 reload the page and note that the changes are not reflected
9 look at the page sources and see that custom.css is not being referenced from its normal place
10 note that it IS being referenced from /themes/_customcss/brooklyncopy/custom.css instead, which is being fulfilled by the WS app as an HTML document despite its .css ending
11 note that the whole _customcss/ directory heirarchy does not even exist on disk
12 scratch your head and ponder where the customisations are in fact being served from, because they do work if you enter them via the /admin 
13 pretty please check your work before munging the system again.

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
