### ISSUE TITLE
Ex VAT or Tax Exclusive prices are displayed after order is placed?

### ISSUE THREAD

**Issue by GoblinGaming** [lightspeedretail/webstore#642]
After someone places an order with us and they then navigate back to the web store, they then see all products displaying prices excluding tax? Which leads them to think we have reduced the prices and they should cancel the order and reorder to save the difference. Eventually the website does display the prices inclusive of tax and all is back to normal.

Obviously this isn't meant to be happening and is causing confusion. 

Any advice is appreciated.

**Comment by gabeguz** [comment]
This has been fixed in the [3.2.2](https://github.com/lightspeedretail/webstore/releases/tag/3.2.2) release.
