### ISSUE TITLE
CartController Calculate Shipping Bug

### ISSUE THREAD

**Issue by brandinchiu** [lightspeedretail/webstore#647]
There's a problem as of 3.2.x with the **CartController**, in the **actionAjaxCalculateShipping** method.  Error handling has been changed, and moved within the method:
>$handleException = function (Exception $e) {
				Yii::log($e->getMessage(), 'error', 'application.'.__CLASS__.".".__FUNCTION__);
				return $this->renderJSON(
					array(
						'result' => 'error',
						'errormsg' => $e->getMessage()
					)
				);
			};

But **$this** doesn't point to the controller anymore as it's beyond scope.  This means no errors are ever printed.

**Comment by gabeguz** [comment]
Thanks for the report @brandinchiu  nice catch.  We'll take a look.

**Comment by brandinchiu** [comment]
On a related note, you seem to have recently changed your checkout view to add a **change()** event to all of your user inputs that runs the **actionAjaxCalculateShipping** method.  While this may make sense from a programming efficiency point of view, it's a nightmare in real-life scenarios.  If I calculate shipping with multiple errors in my form, I'm thrown a new alert message every time I switch fields.

Alerts really shouldn't even be being used in the first place as modern browsers can suppress them, and because they interrupt user-flow.

I highly suggest utilizing inline form errors or bootstrap alerts in future updates.

**Comment by euoia** [comment]
@brandinchiu thanks for the reports. Regarding the piece of code in CartController, the behaviour may depend on PHP version. Which version of PHP did you test on? http://stackoverflow.com/questions/5734011/php-5-4-closure-this-support

On version 5.4.34 it seems to work:
```
$ curl --data "CheckoutForm[test]=test" www.demo.site/cart/ajaxcalculateshipping
{"result":"error","errormsg":"Oops, cannot calculate shipping quite yet. Please complete shipping address information and click Calculate again.\n\nFirst Name cannot be blank.\nLast Name cannot be blank.\nAddress cannot be blank.\nCity cannot be blank.\nCountry cannot be blank.\n"}% 
```

**Comment by euoia** [comment]
@brandinchiu regarding the change() event - we only recalculate shipping when one of the following fields change: country, state, or postal code. I just tested this on the Brooklyn theme. Are you seeing something different?

**Comment by brandinchiu** [comment]
@euoia I believe I'm on 5.3.  If this is a PHP version issue, then that's fine -- but perhaps this should be more clearly documented as 5.3 is a supported version with Web Store.

That is correct, I see the change event on those 3 fields.  This means I'm getting up to 3 alerts when changing shipping details following errors.

**Comment by euoia** [comment]
Hi @brandinchiu - thanks again for the bug report. You're totally correct that 5.3 is documented as a supported version and we are treating this as a bug.

This is linked to WS-4093 in our internal Jira system.

**Comment by gabeguz** [comment]
@brandinchiu we've updated the docs to specify that php 5.4 is now the minimum supported php version.  This is inline with the php project itself, which has declared php 5.3 end of life as of 14 Aug 2014.  See: http://php.net/eol.php
