### ISSUE TITLE
3.2.2 patch missing?

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#648]
We noticed this week that the patch for 3.2.2 went missing. Intentional?
admin/upgrade/index?patch=ws3.2.2upg2015-02-11-2202-180358.zip

**Comment by ottaz** [comment]
Thanks for pointing that out to us @iandberg and apologies for the inconvenience.

We've updated the file so if you attempt to upgrade now you shouldn't have a problem.

**Comment by iandberg** [comment]
Thanks, though it still shows as not working:
![missing-322](https://cloud.githubusercontent.com/assets/583913/6973404/68daa770-d93f-11e4-9092-33e8dda26d52.png)

**Comment by ottaz** [comment]
That URL is no longer valid. Do you have Auto Update enabled or are you clicking the link generated in the Admin Panel?
![applywebstoreupdate](https://cloud.githubusercontent.com/assets/5402601/6973991/e9d8ff6c-d95c-11e4-8055-20c00abe578b.png)

**Comment by iandberg** [comment]
Got it, thanks. Was pasting in my existing path. Works now - thanks
