### ISSUE TITLE
URL issues in 3.2.x

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#649]
A couple of spots in the checkout process don't account for stores in subdirectories:
The store logo looks in /images instead of subdir/images.
![cart-image](https://cloud.githubusercontent.com/assets/583913/6971788/e6e2df40-d933-11e4-9be7-005561e386f2.png)
The 'recover password' button in checkout is linked to /site/forgotpassword instead of subdir/site/forgotpassword

**Comment by gabeguz** [comment]
Thanks for the report @iandberg we'll take a look.

**Comment by gabeguz** [comment]
I've been able to reproduce both issues in development.  I've linked this ticket to WS-4055 (store logo issue) and WS-4056 (forgot password link) in our internal bug tracking database. 

We'll look at adding these two issues to an upcoming sprint.  Thanks again for the report.

**Comment by iandberg** [comment]
Thanks for the quick response! I would look at any other hard-coded urls in index.js as well, if you come across them. Most of our clients have stores in subdirectories. thanks!

**Comment by ottaz** [comment]
This has been fixed as of version [3.2.7](https://github.com/lightspeedretail/webstore/tree/3.2.7).
