### ISSUE TITLE
Problems with Moneris

### ISSUE THREAD

**Issue by brandinchiu** [lightspeedretail/webstore#652]
I have a web store on version 3.1.2 that is having issues with Moneris payments.  Payments are being completed, but the SIM URL is returning a blank page.  Upon further investigation of: **CartController->actionPayment** I've found some errors.

    $retVal =Yii::app()->getComponent($strModule)->gateway_response_process();

If this returns false, there doesn't seem to be anything outputted to the screen.  All of the function's logic is handled when:

    if (is_array($retVal))

Otherwise it just does nothing.

**Comment by ottaz** [comment]
This issue was logged in our tracking system as WS-2553 and fixed in version 3.2.2. Our current version is [3.2.6](https://github.com/lightspeedretail/webstore/tree/3.2.6). So you should be good to go, once the store is upgraded.
