### ISSUE TITLE
Edit Cart modal "Continue Shopping" link keeps /editcart URL

### ISSUE THREAD

**Issue by tylerforesthauser** [lightspeedretail/webstore#653]
I've noticed a strange behaviour with the Edit Cart modal. When you open the modal and then wish to close the modal to continue shopping, you've got 3 options to do this:

![Screenshot Example](https://d1zjcuqflbd5k.cloudfront.net/files/acc_54446/15FyO?response-content-disposition=inline;%20filename=Screen%20Shot%202015-04-20%20at%2011.21.59%20AM.png&Expires=1429554694&Signature=ZQVAfDaTWpXVtXwD6zNUSIKS8bYyvgFwvJ-medorCPE2sNdaMd-OTaN6MTNk14WZMVdS9JNDnoD68vjKNvvPQ47J5ZeeIr9rNFH7H-YxpEnCdU0Cw8EsOoMIXbnErLsSHwIhLSOX820Yrf~I-dT4AB-QxYn91eU6PEBUKiHiq4U_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

When you click the outside areas, the modal closes and the site URL goes back to the proper address. If you click either of the "Continue Shopping" links, the URL remains as: 

example.com**/editcart**

instead of something like:

example.com**/boys-grey-pullover/dp/16**

**Comment by brandinchiu** [comment]
Would also love a resolution to this. It makes page refreshes rather unpleasant for shoppers.

**Comment by euoia** [comment]
Hi @tylerforesthauser. Thanks for reporting this. I have created WS-4118 to track this in our internal bug tracking system.

**Comment by ottaz** [comment]
This has been fixed as of version [3.2.7](https://github.com/lightspeedretail/webstore/tree/3.2.7).
