### ISSUE TITLE
Wishlist 'ship to' address pref

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#656]
Hello,
In wishlist settings, you can enable "Allow buyers to ship my registry items directly..." at an address. However, I don't see the registrant's address in checkout when purchasing a wishlist item. Was curious if this supposed to work or if it's a 'to do'...

Webstore 3.2.6

Thanks!

**Comment by euoia** [comment]
Hi @iandberg. Thanks for the report. This is a known issue and is in our backlog as WS-4016.
