### ISSUE TITLE
missing axia.png

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#657]
Hi,
This is a minor thing, but in testing a new client's checkout, we noticed the thankyou page had a missing axia image. I looked in a default installation of webstore 3.2.6 but couldn't find an image to grab. Is this something that gets dynamically downloaded, or is it supposed to be included?  thanks (see screengrab)
![axia_image](https://cloud.githubusercontent.com/assets/583913/7522420/ea29f49a-f4a9-11e4-9513-5539bd67184c.png)

**Comment by brandinchiu** [comment]
If it's coming from the assets/<code> folder then it means it's being re-generated from a resource already on the server somewhere else.  Not sure what that image is, but it should already be there.

**Comment by iandberg** [comment]
I couldn't find an axia image anywhere within the default webstore installation files, but no big deal. Something to check though.
