### ISSUE TITLE
Checkout address issues

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#658]
webstore 3.2.6
Hello again,
A couple address issues in checkout:
1)
Selecting 'store pickup' in checkout, of course, doesn't prompt for an address. But when choosing credit card as payment, and entering cc info (no address form), we get address validation errors. In-store purchases are kind of stuck here. I think the simple integration modules are ok here, they provide a billing address form (at least with Authorize.net). But I've seen two different advanced integration module examples where there's no billing address form to fill out.

2)
When you create an address in your account area, a phone number is not required. Yet, in checkout it does require a phone number.

Thanks

**Comment by iandberg** [comment]
I should add that item 1 is with guest checkout.

**Comment by gabeguz** [comment]
Thanks for the report @iandberg We'll take a look.

**Comment by iandberg** [comment]
Also, wanted to add:
If you're logged in with a saved address:
Choose In-Store pickup
Don't fill out the In-store form
Click 'proceed'
No validation errors appear

**Comment by iandberg** [comment]
It appears that if you set 'store pickup' to apply to 'everywhere', then the billing address form shows. Though with this new cart, restricting 'store pickup' to a region seems not applicable, as 'store pickup' shows as an option before any location is given.

**Comment by ottaz** [comment]
Apologies for the time taken to reply here @iandberg but yes you're right.

The idea of the user experience is such that Store pickup is always immediately available if the store offers it. This way a shopper can bypass the requirement of filling in a shipping address - why would a shipping address be required if the buyer plans to pick the item up, right?

This then conflicts with the location restriction settings in the admin panel that are available to all shipping methods.

The reasn we can't hide the location restriction on Store pickup in the admin panel is that it will affect backwards compatibility on older themes where you do have to define a shipping address before you see any shipping options, which include Store pickup.

As a result, to work on Brooklyn2014, the 'Everywhere' setting is required for Store Pickup. An effective way of notifying merchants of these nuances preferably within the admin panel would be beneficial.
