### ISSUE TITLE
Incorrect link/image paths when installed in subdirectory

### ISSUE THREAD

**Issue by tylerforesthauser** [lightspeedretail/webstore#659]
If your Web Store is installed in a subdirectory, there are a couple of issues during the Checkout process:

1) The header image path is not correct so the header image is not displayed.
2) On the Payment page, if you choose to have add a Billing Address, the link path is not correct and you will receive a 404 error.

**Comment by gabeguz** [comment]
Thanks for the report @tylerforesthauser -- The image issue was fixed last week, and should be making its way into 3.2.7.  I'll investigate the 404 today and get back to you.

**Comment by gabeguz** [comment]
The image issue is linked to our internal tracking system as:  WS-4055

**Comment by tylerforesthauser** [comment]
To lead you to the specific line where the error is generated, it's line 120 of /core/protected/views-cities3/checkout/paymentsimpleaddress.php.

```<?php echo CHtml::link(Yii::t('checkout', 'Add New Address'), '/checkout/newaddress?type=billing', array('class' => 'small button')); ?>```

If I'm not mistaken, it should be more like:

```<?php echo CHtml::link(Yii::t('checkout', 'Add New Address'), Yii::app()->createUrl('/checkout/newaddress?type=billing'), array('class' => 'small button')); ?>```

**Comment by gabeguz** [comment]
@tylerforesthauser thanks for the direct reference, confirmed the issue, and have applied your patch, but it won't be live until 3.2.8.  The image issue should be live later today, we're pushing 3.2.7 out now.

**Comment by ottaz** [comment]
This issue has been fixed as of version [3.2.9](https://github.com/lightspeedretail/webstore/tree/3.2.9).
