### ISSUE TITLE
update to 3.2.8

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#661]
Hello,
I have a client who is currently on 3.2.7. The admin panel prompts for an update to 3.2.8, however when clicked, it says I need 3.2.7.1 first, though it never prompted for 3.2.7.1. Workaround? thanks!

![update_to_328](https://cloud.githubusercontent.com/assets/583913/7658243/61e20632-faed-11e4-9daf-10c44c04e88b.png)

**Comment by ottaz** [comment]
Have them try again @iandberg . If the prompt in the admin panel is showing 3.2.8, they should just have to reload the page to get the 3.2.7.1 prompt. Then they can go from 3.2.7.1 to 3.2.8. Let us know how it goes.

**Comment by iandberg** [comment]
Thank you - working now
