### ISSUE TITLE
Sorting in custom pages

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#662]
Hello,
A minor issue we noticed. The product sorting criteria doesn't seem to affect custom pages (using the grid layout)

**Comment by euoia** [comment]
Hi @iandberg. Thanks for the report. We're aware of this issue and are working on fixing it for our next release. We're tracking it internally as WS-999.

**Comment by ottaz** [comment]
This has now been fixed as of version [3.2.9](https://github.com/lightspeedretail/webstore/tree/3.2.9)

**Comment by tylerforesthauser** [comment]
Am I crazy or is this actually still not fixed? It seems because the custom page product grid is still generated as a search result, the products are still being displayed by "relevance" and not respecting the sorting criteria set in the admin panel.

**Comment by jsfehler** [comment]
Sorry for the confusion, this issue was actually WS-3189, which has not been fixed yet.

**Comment by jsfehler** [comment]
This issue has been fixed in version 3.3.0.
