### ISSUE TITLE
Lightspeed Upgrade of 3.0.0 to 3.0.1 stuck in infinite loop

### ISSUE THREAD

**Issue by garrett-eclipse** [lightspeedretail/webstore#667]
Hello,

Hoping someone can help me, I recently upgraded to 3.0.0 and am following these instructions to do the 3.0.1 upgrade;
http://www.lightspeedpos.com/onsite-support/lightspeed-ecommerce/how-to-upgrade-web-store/#migrating3.0

I've downloaded the dmg from here;
http://downloads.xsilva.net/webstore/upgrade

And have uploaded the upgrade folder to my server, I navigated to /store/upgrade/upgrade.php and it began the process with everything looking casual, but once it finished it simply reloaded the page and redid the whole process.

Any idea what's going on? I was thinking it was upgrading through all versions to 3.2.8 but it's been going long enough for me to realize that's probably not the case.

Help please,
Thank you

**Comment by garrett-eclipse** [comment]
Alright so it finally bombed out with an alert saying;
"The install process has become unresponsive. This may indicate a problem with the database. Please contact technical support for additional information. Error information may be available in the xlsws_log table of your database for troubleshooting purposes."

The export of the xlsws_log table - http://silkroadteastore.eclipsedev.tk/store/xlsws_log.sql.zip

As you can see the last few rows occuring today have the error;
`system.db.CDbCommand
CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty. The SQL statement executed was: .`
`exception.CDbException
exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty' in /home/dev/public_html/silkroadteastore/store/core/framework/db/CDbCommand.php:358
Stack trace:
#0 /home/dev/public_html/silkroadteastore/store/core/protected/modules/admin/controllers/UpgradeController.php(316): CDbCommand->execute()
#1 /home/dev/public_html/silkroadteastore/store/core/protected/modules/admin/controllers/UpgradeController.php(43): UpgradeController->actionDatabaseUpgrade('65')
#2 /home/dev/public_html/silkroadteastore/store/core/framework/web/actions/CInlineAction.php(49): UpgradeController->actionUpgrayedd()
#3 /home/dev/public_html/silkroadteastore/store/core/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /home/dev/public_html/silkroadteastore/store/core/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /home/dev/public_html/silkroadteastore/store/core/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /home/dev/public_html/silkroadteastore/store/core/framework/web/CWebApplication.php(282): CController->run('upgrayedd')
#7 /home/dev/public_html/silkroadteastore/store/core/framework/web/CWebApplication.php(141): CWebApplication->runController('admin/upgrade/u...')
#8 /home/dev/public_html/silkroadteastore/store/core/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /home/dev/public_html/silkroadteastore/store/index.php(19): CApplication->run()
#10 {main}
REQUEST_URI=/store/admin/upgrade/upgrayedd
HTTP_REFERER=http://silkroadteastore.eclipsedev.tk/store/admin/upgrade/index
---`

Any thoughts on why this failed? Reloading the admin just started the process over again so I removed the /upgrade folder from my host to allow me access to the webstore again. But sadly this didn't do anything, even with the /upgrade folder gone it still redirects /admin to /admin/upgrade/index which runs the infinite loop of the process.

Appreciate any ideas,
Thanks

**Comment by brandinchiu** [comment]
Considering how enormous the upgrade process from 2.x.x to 3.x.x, and then again from 3.x.x to 3.2.x, I would strongly consider installing a fresh copy of web store on your server, fully updating it to 3.2.9, and then starting over with your theming (if you have custom templates).  Your life will be made significantly easier.

Yes, you will need to perform a store reset, and yes, this could potentially take time, but at least you can be 100% sure that you're moving forward.

**Comment by garrett-eclipse** [comment]
Thanks @brandinchiu is it possibly to migrate from 2.5.1 to 3.2.9 through the install.php and keep the product information from the database as is done from any 2.0.9+ > 3.0.0 migration as outlined here;
http://www.lightspeedpos.com/onsite-support/lightspeed-ecommerce/how-to-upgrade-web-store/#migrating3.0
Is it the same process or is there alternate instructions for such a thing.
Appreciated

**Comment by brandinchiu** [comment]
If I remember correctly, the update process from 2.5.x is significantly easier, since both systems are already using the new back end. There shouldn't be any alternate instructions. The file structure will remain the same, but the database will change a bit (not enough to require a store reset though).

**Comment by garrett-eclipse** [comment]
Thanks @brandinchiu I used the 3.2.9 installer with no issue so I guess you don't need to do 3.0.0 then 3.0.1 etc. as the documentation indicated. Everything went much smoother when I just jumped from 2.5.1 to 3.2.9
