### ISSUE TITLE
CData generated by Web Store conflicting with custom changes

### ISSUE THREAD

**Issue by brandinchiu** [lightspeedretail/webstore#668]
At the bottom of the Web Store markup, from the product detail page, CData is inserted by Yii to handle some of the ajax calls.  One of these fragments:

    if($.isFunction(bindZoom))bindZoom();

Is causing problems because I'm not using your photo extension.  Where is this being generated so I can remove it? Whenever the matrix is changed, JS crashes because this line fails to find the bindZoom plugin.

**Comment by tylerforesthauser** [comment]
@brandinchiu This code is all happening in an extension.

`/core/protected/extensions/wsmenu/wsmatrixselector.php - line 261`

Of course you can copy the `wsmenu` directory to `/custom/extensions` and change the line `<?php $this->widget('ext.wsmenu.wsmatrixselector', array(` to `<?php $this->widget('custom.wsmenu.wsmatrixselector', array(` in your Product Details view file.

Hope that helps!
