### ISSUE TITLE
Helper is not defined error on custom theme.

### ISSUE THREAD

**Issue by brandinchiu** [lightspeedretail/webstore#671]
In the myaccount/index.php view, there is a new script added with
    var helper = new Helper();

I have not modified any view files in this folder in my custom theme, but Web Store can't see to find that class.  Where is the base class included so I can go back and make sure I'm linking it properly?

**Comment by ottaz** [comment]
@brandinchiu You should have a file called [Helper.js](https://github.com/lightspeedretail/webstore/blob/master/core/protected/extensions/wsaccount/assets/Helper.js) in the wsaccount extension. This is the class that Helper refers to in the index file.

Let us know if you have continue to have issues.
