### ISSUE TITLE
Bad code in _customerreceipt

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#672]
Webstore 3.3.0
/core/protected/views-cities/mail/_customerreceipt.php

The brackets in the following code causes parsing error:
<?=
	CHtml::link(
		Yii::t('email', 'Order #:') . ' ' . '<span>' . $cart->id_str . '</span>',
		_xls_url_common_to_custom(
			Yii::app()->controller->createAbsoluteUrl(
				'cart/receipt',
				['getuid' => $cart->linkid]
			)
		),
		array(
			'target' => '_blank',
			'style' => 'color: #3287cc;text-decoration: none;'
		)
	);
?>

**Comment by euoia** [comment]
Hi @iandberg - thanks for the report!

The square bracket syntax for arrays was added in PHP 5.4. We are no longer supporting PHP 5.3 and earlier. See:
http://www.lightspeedpos.com/onsite-support/lightspeed-ecommerce/what-are-the-web-hosting-requirements-for-lightspeed-web-store/

**Comment by iandberg** [comment]
thanks!
