### ISSUE TITLE
HTTP 500 on newly installed webstore

### ISSUE THREAD

**Issue by senguttuvang** [lightspeedretail/webstore#675]
I installed a new webstore and it throws exception when navigating to the home page.

Here's the stack trace of the error. I think lsid should be checked for non-emptiness before accesing $taxcode->lsid.
```

Stack trace:
#0 core/framework/web/auth/CWebUser.php(246): WebUser->afterLogin()
#1 core/protected/models/forms/LoginForm.php(113): WebUser->login()
#2 core/protected/controllers/MyaccountController.php(503): LoginForm->login()
#3 core/protected/controllers/MyaccountController.php(192): MyaccountController->createAndLogin()
#4 core/framework/web/actions/CInlineAction.php(49): MyaccountController->actionEdit()
#5 core/framework/web/CController.php(308): CInlineAction->runWithParams()
#6 core/framework/web/CController.php(286): MyaccountController->runAction()
#7 core/framework/web/CController.php(265): MyaccountController->runActionWithFilters()
#8 core/framework/web/CWebApplication.php(282): MyaccountController->run()
#9 core/framework/web/CWebApplication.php(141): WsWebApplication->runController()
#10 core/framework/base/CApplication.php(180): WsWebApplication->processRequest()
#11 index.php(19): WsWebApplication->run()
REQUEST_URI=/myaccount/edit
```

**Comment by jsfehler** [comment]
Hi,

Do you have taxes sync'd from lightspeed?
This error normally only occurs if taxes do not exist in Web Store.
Currently we don't support the non-existence of taxes.

**Comment by senguttuvang** [comment]
Nope, I do not have access to Mac or LightSpeed software to sync data back to my machine. 

Yes, I understand the issue is due to missing taxes since I do not this data, but instead of HTTP 500, the system would have gracefully handled the situation. A simple empty check would have prevented this issue.

**Comment by ottaz** [comment]
While the Webstore is open source, it is meant to work with Lightspeed software and as such it is important for our support and developers that exceptions and errors are thrown and logged if necessary data is missing.

So please understand, if you are using the software outside of this scenario you will continue to encounter errors like this.
