### ISSUE TITLE
Duplicate category created in Web Store when original category get renamed at LSOS

### ISSUE THREAD

**Issue by senguttuvang** [lightspeedretail/webstore#678]
We noticed duplicate category names are getting generated when the original category get renamed at LSOS end. Categories are supposed to be unique across the web-store, but I have noticed 2~3 duplicates for each category that had been renamed.

It appears that SOAP connector is unable to locate the original record so it create new duplicate category instead of updating it.

**Comment by ottaz** [comment]
Hi @senguttuvang,

Are you using Lightspeed Onsite or Retail? Be sure that you re-assign these new or renamed categories to your products. Any product that still has one of the old categories will force Webstore to keep that category live.
