### ISSUE TITLE
On installation end the documentation link in description is incorrect

### ISSUE THREAD

**Issue by tebazil** [lightspeedretail/webstore#682]
![screenshot_092](https://cloud.githubusercontent.com/assets/2419721/15501131/819f1912-21b4-11e6-9fb5-fa256c9d152d.png)

See webstore setup guide

**Comment by ottaz** [comment]
Thank you @tebazil 
This issue is being tracked internally as WS-4535.

**Comment by ottaz** [comment]
This issue has been fixed in [v3.3.4](https://github.com/lightspeedretail/webstore/tree/3.3.4)
