### ISSUE TITLE
Install script failing 

### ISSUE THREAD

**Issue by obzidi4n** [lightspeedretail/webstore#683]
Hi there -

Running Ubuntu 16.04 with Apache and PHP7.  

Am passing the PHP extensions check but the script is hanging at "Downloading Default Template" while the progress bar message "Server appears to be throttling connections, setting delay to X seconds" hangs on an infinite loop.

Seeing this error in apache logs:

```
PHP Notice:  Use of undefined constant MYSQL_NUM - assumed 'MYSQL_NUM' in /var/www/webstore/install.php on line 15
PHP Notice:  Use of undefined constant MYSQL_ASSOC - assumed 'MYSQL_ASSOC' in /var/www/webstore/install.php on line 16
PHP Notice:  Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in /var/www/webstore/install.php on line 17
```

**Comment by ottaz** [comment]
Hi @obzidi4n .

PHP 7 is a bit too new to handle Webstore, I would recommend any version between 5.4 and 5.6.

**Comment by satyakishores** [comment]
I am also getting the same error. Is this error resolved for php7?

**Comment by ottaz** [comment]
Hi @satyakishores 

We are no longer actively developing Web Store, so the issues it will have with up to date versions of PHP and other various dependent libraries will persist.
