### ISSUE TITLE
how to call product images 512x512 pixels ?

### ISSUE THREAD

**Issue by birdawn** [lightspeedretail/webstore#686]
Hello,

In the product template there are a 256x256 container pictures with the magnifyng glass that doesn't have too much sense because the container is too small.

I try to build a bigger container 512x512 and fit the photo that already exist with 512x512 pixels.
Do anyone known how to call this picture?  I can't find or see the variable to call it...

Thank you in advance, Juan

**Comment by ottaz** [comment]
Hi Juan,

You can update the dimensions of the image that should show on the product detail page via the theme admin form. Take a look at this wiki article for guidance, https://github.com/lightspeedretail/webstore/wiki/Creating-a-Theme-Admin-Panel

**Comment by birdawn** [comment]
Thank you very much. This solution my issue!

**Comment by ottaz** [comment]
Your welcome!
