### ISSUE TITLE
createAbsoluteUrl

### ISSUE THREAD

**Issue by birdawn** [lightspeedretail/webstore#688]
Hello,

I have a repetitive log regarding createAbsolutUrl:
Function deprecated, should use $this->createAbsoluteUrl instead
in /var/www/vhosts/originalonweb.com/httpdocs/core/protected/components/helpers.php (49)
in /var/www/vhosts/originalonweb.com/httpdocs/themes/monacocopy1/views/site/_navigation.php (74)
in /var/www/vhosts/originalonweb.com/httpdocs/themes/monacocopy1/views/layouts/main.php (12)
What doesn't mean? 

I read some information in a yii forum http://www.yiiframework.com/forum/index.php/topic/14825-problem-with-createurl-and-createabsoluteurl-in-console-application/

And I add the code in console.php but doesn't work. Anyone know  what I should do?
Do I need to add this:

        'request' => array(
            'hostInfo' => 'https://domainname.com',
            'baseUrl' => '',
            'scriptUrl' => '',
        ),
To helpers.php, navigation.php and main.php???????????
Than you in advance, Juan

**Comment by ottaz** [comment]
The issue is the call to the helper function `_xls_site_url()` which contains that log instruction.
The easiest thing to do is remove the line of code inside the `_xls_site_url()` function that logs that message. Otherwise, you need to update `_xls_site_url` to `Yii:app()->createAbsoluteUrl()` instead, everywhere your code calls it.

**Comment by birdawn** [comment]
When I edit the file /core/protected/components/helpers.php and remove this code:

function _xls_site_url($strUrlPath = '')
// @codingStandardsIgnoreEnd
{
	Yii::log("Function deprecated, should use \$this->createAbsoluteUrl instead", 'info', 'application.'.__CLASS__.".".__FUNCTION__);
	return Yii::app()->createAbsoluteUrl($strUrlPath);
}

Then my homepage only show a menu in html, any idea what I’m doing wrong?

Thank you, Juan

**Comment by ottaz** [comment]
Just remove this line,
```php
Yii::log("Function deprecated, should use \$this->createAbsoluteUrl instead", 'info', 'application.'.__CLASS__.".".__FUNCTION__);
```

That will stop the repetitive log.
