### ISSUE TITLE
How to add new product

### ISSUE THREAD

**Issue by sankar1061** [lightspeedretail/webstore#689]
We have installed lightspeed web store in local server successfully. In web store admin does not find the "**create new product**" option. _So how to add new product or import the product_.

**Comment by ottaz** [comment]
Web Store is the now obsolete and end-of-life eCommerce solution that was tailored to work with Lightspeed's Onsite point-of-sale software. Product information is supposed to be synced from Onsite to Web Store. Unless you have that software (Onsite) installed and licensed to use Web Store, then you will need to build your own 'connector' or 'bridge' application to populate Web Store with product data.

As I mentioned, we no longer officially support Web Store. It is really old, the code is written in outdated PHP and is no longer actively developed. You are free to post questions you may have in here, but answers may not come as quickly as you would like.

Truthfully, I would suggest you invest in a different solution.
